apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: meal-planner
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: meal-planner
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: meal-planner
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
