apiVersion: v1
kind: ConfigMap
metadata:
  name: meal-planner-config
  namespace: meal-planner
  labels:
    app.kubernetes.io/name: meal-planner
    app.kubernetes.io/part-of: meal-planner
data:
  API_BASE_URL: "http://api"
  AUTH0_DEFAULT_RETURN_TO: "https://meal-planner.ashleyhollis.com"
  AUTH0_ALLOWED_RETURN_ORIGINS: "https://meal-planner.ashleyhollis.com"
  AUTH0_SESSION_COOKIE_NAME: "meal_planner_session"
  AUTH0_SESSION_COOKIE_SAMESITE: "lax"
