apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/part-of: shared-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-cluster
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-tunnel-token
