apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ytsumm-acr-pull
  labels:
    app.kubernetes.io/name: yt-summarizer
    app.kubernetes.io/component: image-pull
spec:
  externalSecretName: acr-pull-secret
  namespaceSelectors:
    - matchLabels:
        app.kubernetes.io/part-of: yt-summarizer
  refreshTime: 5m
  externalSecretSpec:
    refreshInterval: 20h
    secretStoreRef:
      name: acr-pull-source
      kind: ClusterSecretStore
    target:
      name: acr-pull-secret
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
    dataFrom:
      - extract:
          key: acr-pull-secret-source
