apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-pull-secret-source
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: yt-summarizer
    app.kubernetes.io/component: image-pull
spec:
  refreshInterval: 20h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ACRAccessToken
          name: ytsumm-acr-pull
  target:
    name: acr-pull-secret-source
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "acrytsummprdci.azurecr.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}"
              }
            }
          }
